### ISSUE TITLE
Update dependancies

### ISSUE THREAD

**Issue by neb0lle** [acmpesuecc/swype#2]
### Update dependancies without breaking anything.
- Update all dependancies to its latest version in the `package.json` file

**Comment by Shresht-Ahuja** [comment]
can you assign this to me

**Comment by VulcanRaven737** [comment]
Hey can you assign this issue to me!

**Comment by neb0lle** [comment]
!assign  @VulcanRaven737

**Comment by kdb04** [comment]
can i be assigned?

**Comment by VulcanRaven737** [comment]
I already finished it lol

**Comment by neb0lle** [comment]
!assign @VulcanRaven737
