### ISSUE TITLE
Pointerlock bug

### ISSUE THREAD

**Issue by neb0lle** [acmpesuecc/swype#3]
### Clicking GUI objects locks pointer
- make the pointer not lock on clicking GUI related stuff.

**Comment by Keeru-2005** [comment]
please assign this to me @neb0lle

**Comment by neb0lle** [comment]
!assign @Keeru-2005

**Comment by RahulBiju-dev** [comment]
Can i be assigned to this

**Comment by neb0lle** [comment]
!assign @RecklessSoftwareGuy

**Comment by neb0lle** [comment]
!assign @RecklessSoftwareGuy

**Comment by neb0lle** [comment]
!deassign

**Comment by pratham-exe** [comment]
can u assign this

**Comment by neb0lle** [comment]
!assign @pratham-exe
